browser.runtime.onMessage.addListener((msg, sender, sendResponse) => {
  if (msg === "send_youtube_cookies") {
    getYoutubeCookies(sendToLocalhost);
  }
});

function getYoutubeCookies(callback) {
  browser.cookies.getAll({ domain: "youtube.com" }).then((cookies) => {
    const netscapeCookies = cookies.map(c => {
      return [
        c.domain.startsWith('.') ? c.domain : '.' + c.domain,
        "TRUE",
        c.path,
        c.secure ? "TRUE" : "FALSE",
        Math.floor((c.expirationDate || 0)),
        c.name,
        c.value
      ].join('\t');
    }).join('\n');
    callback(netscapeCookies);
  });
}

function sendToLocalhost(data) {
  const header = "# Netscape HTTP Cookie File\n# This file is generated by VRCVideoCacher.  Do not edit.\n\n";
  const formattedData = header + data;
  
  fetch("http://localhost:9696/api/youtube-cookies", {
    method: "POST",
    headers: { "Content-Type": "text/plain" },
    body: formattedData
  });
}

browser.runtime.onInstalled.addListener(() => {
  getYoutubeCookies(sendToLocalhost);
});