let debounceTimer = null;
const debounce = (func, delay) => {
  return (...args) => {
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => func.apply(this, args), delay);
  };
};

export function getYoutubeCookies() {
  getAndSendYoutubeCookies();
}

export function getYoutubeCookiesDebounce(changeInfo) {
  console.log("Cookies change detected:", changeInfo?.cookie?.name);
  debounce(getAndSendYoutubeCookies, 5000)();
}

const getAllYouTubeCookies = async () => {
  const details = {
    domain: "youtube.com",

    storeId: await getCurrentCookieStoreId(),
  };
  const detailsWithPartitionKey = {
    ...details,
    partitionKey: {
      topLevelSite: "https://youtube.com",
    },
  };

  // https://github.com/kairi003/Get-cookies.txt-LOCALLY/tree/master/src/modules/get_all_cookies.mjs#L9-L17
  // Error handling for browsers that do not support partitionKey, such as chrome < 119.
  // `chrome.cookies.getAll()` returns Promise but cannot directly catch() chain.
  const cookiesWithPartitionKey = await Promise.resolve()
    .then(() => chrome.cookies.getAll(detailsWithPartitionKey))
    .catch(() => []);
  const cookies = await chrome.cookies.getAll(details);
  return [...cookies, ...cookiesWithPartitionKey];
};

const getCurrentCookieStoreId = async () => {
  // If the extension is in split incognito mode, return undefined to choose the default store.
  if (chrome.runtime.getManifest().incognito === "split") {
    return undefined;
  }

  // Firefox supports the `tab.cookieStoreId` property.
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  if (tab?.cookieStoreId) {
    return tab.cookieStoreId;
  }

  // Chrome does not support the `tab.cookieStoreId` property.
  const stores = await chrome.cookies.getAllCookieStores();
  return stores.find((store) => store.tabIds.includes(tab?.id))?.id;
};

const getAndSendYoutubeCookies = async () => {
  const cookies = await getAllYouTubeCookies();
  console.log(`Fetched ${cookies.length} YouTube cookies`);
  const header = [
    "# Netscape HTTP Cookie File",
    "# This file is generated by VRCVideoCacher.  Do not edit.",
    "",
  ].join("\n");
  const netscapeCookies = cookies
    .map((c) => {
      const domain = c.domain.startsWith('.') ? c.domain : '.' + c.domain;
      return [
        domain,
        "TRUE",
        c.path,
        c.secure ? "TRUE" : "FALSE",
        Math.floor(c.expirationDate || 0),
        c.name,
        c.value,
      ].join("\t");
    })
    .join("\n");
  const formattedData = header + netscapeCookies + "\n";
  await sendToLocalhost(formattedData);
};

const sendToLocalhost = async (data) => {
  await fetch("http://127.0.0.1:9696/api/youtube-cookies", {
    method: "POST",
    headers: { "Content-Type": "text/plain" },
    body: data,
  });
  console.log("YouTube cookies sent to VRCVideoCacher.");
};
